### ISSUE TITLE
Visium HD proseg error "ScaleTooSmall"

### ISSUE THREAD

**Issue by rachelgriffard** [dcjones/proseg#120]
Hello!

I notice this error initially addressed in #109, but I am not finding the resolution I am looking for.

I have six Visium HD samples. They were all run through SpaceRanger with the same settings, and then run in proseg with all the default parameters. Interestingly, three of my samples ran without error. On the other hand, three errored out with the same message:

```bash
proseg-3.0.8/src/sampler/paramsampler.rs:119:18:
called `Result::unwrap()` on an `Err` value: ScaleTooSmall
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

It is worth noting that there are no clear differences between the three samples that ran and those that did not (not split by experiment groups, etc.). They also seem to have similar metrics in the SpaceRanger "Cell Segmentation Metrics" tab.

I appreciate any insight you might be able to provide for this!

**Comment by rachelgriffard** [comment]
@dcjones These are the results I am seeing when I run with RUST_LOG=info. I am not seeing anything about component population. Might I need to run RUST_BACKTRACE=full to get that information?

```
thread 'main' panicked at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proseg-3.0.8/src/sampler/paramsampler.rs:119:18:
called `Result::unwrap()` on an `Err` value: ScaleTooSmall
stack backtrace:
   0: __rustc::rust_begin_unwind
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/std/src/panicking.rs:697:5
   1: core::panicking::panic_fmt
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/panicking.rs:75:14
   2: core::result::unwrap_failed
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/result.rs:1732:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/result.rs:1137:23
   4: proseg::sampler::paramsampler::ParamSampler::sample_volume_params::{{closure}}
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proseg-3.0.8/src/sampler/paramsampler.rs:115:23
   5: ndarray::zip::Zip<(P1,P2),D>::for_each::{{closure}}
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ndarray-0.16.1/src/zip/mod.rs:585:41
   6: ndarray::zip::Zip<P,D>::inner
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ndarray-0.16.1/src/zip/mod.rs:355:31
   7: ndarray::zip::Zip<P,D>::for_each_core_contiguous
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ndarray-0.16.1/src/zip/mod.rs:334:18
   8: ndarray::zip::Zip<P,D>::for_each_core
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ndarray-0.16.1/src/zip/mod.rs:319:13
   9: ndarray::zip::Zip<(P1,P2),D>::for_each
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/ndarray-0.16.1/src/zip/mod.rs:583:17
  10: proseg::sampler::paramsampler::ParamSampler::sample_volume_params
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proseg-3.0.8/src/sampler/paramsampler.rs:112:9
  11: proseg::sampler::paramsampler::ParamSampler::sample
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proseg-3.0.8/src/sampler/paramsampler.rs:37:9
  12: proseg::main
             at .cargo/registry/src/index.crates.io-1949cf8c6b5b557f/proseg-3.0.8/src/main.rs:902:9
  13: core::ops::function::FnOnce::call_once
             at /rustc/6b00bc3880198600130e1cf62b8f8a93494488cc/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
Finished processing D1_120_13-5-dko
Thu Oct 16 16:13:36 CDT 2025
```

**Comment by rachelgriffard** [comment]
@uthsavc I was not able to find a solution to this. I am wondering if @dcjones might be able to give some insight?

**Comment by dcjones** [comment]
Hi, I was able to reproduce the issue and figured out what was happening. It should be fixed in version 3.0.12 which a just released.

**Comment by uthsavc** [comment]
@dcjones thank you so much for the quick turnaround!! Proseg works now on the 10x VisiumHD small intestine data.

Question: is there any code (or a tutorial?) to visualize the segmented cells on top of the histology image in the spaceranger output? the histology image isn't in the Proseg `.zarr` output file. Furthermore the coordinate system in the output file are different than the coordinates in the original data (roughly scaled by ~3.7?). I tried transforming the proseg coordinates but they are somewhat unaligned with the histology image.

Thank you so much!

<img width="495" height="526" alt="Image" src="https://github.com/user-attachments/assets/053860cb-66d8-474d-bdfe-132134eaf041" />

**Comment by samkleeman1** [comment]
As a linked point I have been struggling to use the proseg Visium HD outputs to run spaceranger, in order to be able to view the cell segmentations in high resolution in Visium browser.
I used to proseg-to-baysor conversion script recommended for Xenium to break up the multi-polygon objects
Then I tried to convert microns to pixels with the following script but I am still seeing significant misalignment. Very grateful for any suggestions to get this to work.

```
import json
import shapely.geometry
import shapely.wkt
import pandas as pd
import geopandas as gpd

input_path = "/grid/janowitz/home/data/teratoma/visium/jan26/process/visium_a1/proseg-to-baysor-cell-polygons.geojson"
output_path = "/grid/janowitz/home/data/teratoma/visium/jan26/process/visium_a1/proseg_clean.geojson"

# 1. Load using Geopandas directly (handles 'geometries', 'features', etc. automatically)
try:
    gdf = gpd.read_file(input_path)
    print(f"Successfully loaded {len(gdf)} shapes.")
except Exception as e:
    print(f"Standard load failed, trying manual json load: {e}")
    with open(input_path, 'r') as f:
        data = json.load(f)
        # If it's a list of geometries directly or another structure
        gdf = gpd.GeoDataFrame.from_features(data) if 'features' in data else gpd.GeoDataFrame(geometry=[shapely.geometry.shape(g) for g in data.get('geometries', data)])

# 2. Scale from Microns to Pixels
mpp = 0.2648119168882517
gdf.geometry = gdf.geometry.scale(xfact=1/mpp, yfact=1/mpp, origin=(0, 0))

# 3. Fix Geometry Topology & Explode MultiPolygons
gdf = gdf.explode(index_parts=False)

def clean_geom(geom):
    if geom is None: return None
    if not geom.is_valid:
        geom = geom.buffer(0)
    # Rounding to 3 decimals avoids floating point noise
    return shapely.wkt.loads(shapely.wkt.dumps(geom, rounding_precision=3))

gdf.geometry = gdf.geometry.apply(clean_geom)
gdf = gdf[gdf.geometry.notnull()] # Remove any null geometries

# 4. Manual GeoJSON Construction for SpaceRanger Compatibility
features = []
for i, row in gdf.iterrows():
    geom_mapping = shapely.geometry.mapping(row.geometry)
    
    # Try to find a cell ID in the original data, otherwise use the index
    cell_id = row.get('cell', row.get('cell_id', i))
    
    feature = {
        "type": "Feature",
        "id": int(cell_id),
        "geometry": geom_mapping,
        "properties": {
            "object_type": "cell",
            "cell": int(cell_id)
        }
    }
    features.append(feature)

geojson_final = {
    "type": "FeatureCollection",
    "features": features
}

# 5. Save final file
with open(output_path, "w") as f:
    json.dump(geojson_final, f)

print(f"Exported {len(features)} features to {output_path}")
```

**Comment by dcjones** [comment]
I got visualization working on napari, which lead me to realize I didn't quite understand how the scaling worked. Hopefully you can adapt this to your workflow, or use this to visualize polygons on top of the tissue image:

```python
import spatialdata
import napari_spatialdata
from spatialdata.transformations import Scale
from imageio.v3 import imread
import json

# napari-spatialdata will simplify the polygons by default, which can
# significantly distorts proseg polygons. The only workaround currently
# is to set this constant to some number larger than the number of cells,
# which will result in accurate polygons but take longer to load.
napari_spatialdata.constants.config.POLYGON_THRESHOLD = 1e9

proseg_output_filename = "proseg-output.zarr"
tissue_image_filename = "data/spatial/tissue_hires_image.png"
scalefactors_filename = "data/spatial/scalefactors_json.json"

# Read scale factors
scalefactors = json.load(open(scalefactors_filename))
scale = scalefactors["microns_per_pixel"] / scalefactors["tissue_hires_scalef"]

# Read and scale image. I'm using the png tissue image, but I think this should be able to
# be done with the original tiff, just without the tissue_hires_scalef.
img_data = imread(tissue_image_filename)
parsed_img = spatialdata.models.Image2DModel.parse(
    img_data,
    dims=("x", "y", "c"),
    c_coords=("r", "g", "b"),
    transformations={"global": Scale([scale, scale, 1.0], ("x", "y", "c"))}
)

# Read spatialdata and insert image
sdata = spatialdata.read_zarr("proseg-output.zarr")
sdata.images["tissue_image"] = parsed_img

# This sparse array that proseg writes gets converted into a dense array by
# napari_spatialdata, blowing up memory usage. So just remove it.
del sdata.tables["table"].obsp["transition_counts"]

napari_spatialdata.Interactive(sdata)
```

This takes a while to load, but here's what it looks like on this [public prostate dataset](https://www.10xgenomics.com/datasets/visium-hd-cytassist-gene-expression-libraries-human-prostate-cancer-ffpe):

<img width="856" height="720" alt="Image" src="https://github.com/user-attachments/assets/96e2dbc8-df67-4e6a-bf18-ce4239cd41f4" />
